version: "3"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgresdb
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  news:
    build:
      context: .
      dockerfile: Dockerfile
    image: bigspawn/music-news
    container_name: news
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      BOT_ID: ""
      CHAT_ID: ""
      DB_URL: ""
    ports:
      - "19091:9091"
    depends_on:
      - postgres
  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: bigspawn/music-news
    container_name: notifier
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      NOTIFY: "true"
      BOT_ID: ""
      CHAT_ID: ""
      DB_URL: ""
      SONG_API_KEY: ""
    ports:
      - "19092:9091"
    depends_on:
      - postgres
      - news
