name: Create and publish a Docker image

on:
  push:
    branches: [ 'master' ]
    tags:
      - v1.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CI_TOKEN }}
